### ISSUE TITLE
"dd" command breaks H, M, L jumps

### ISSUE THREAD

**Issue by bmatzelle** [nosami/XSVim#253] opened 2019-04-10 18:46 UTC
The jumps that were added in [this ticket](https://github.com/nosami/XSVim/issues/55) do not work.  

I am running Visual Studio on macOS Mojave with Vim 0.65.0.80.

**Comment by nosami** [comment] 2019-04-11 10:40
What happens when you press H, M, L?

**Comment by bmatzelle** [comment] 2019-04-11 13:16
I just updated to Visual Studio 8.0.2 this morning and now it's working.  I hadn't restarted it in a long time so I wonder if that was the problem or if the update fixed it?  Either way it's working fine now so I'm closing this ticket.  Thanks!

**Comment by bmatzelle** [comment] 2019-04-15 13:38
I re-opened this ticket because I figured out how to reproduce the issue.  It's fairly simple.  

1. Run the "dd" command to delete a line
2. Try hitting H, M or L.  Nothing happens.

**Comment by nosami** [comment] 2019-04-15 14:37
Seems to be working fine here for me.

**Comment by nosami** [comment] 2019-04-15 14:38
Are there any errors logged? Look in `Help -> Open Log Directory` then look at Ide.log

**Comment by bmatzelle** [comment] 2019-04-15 14:56
Yes.  The same errors are showing up multiple times.  I've attached the entire log.  

[Ide.2019-04-15__09-33-46.log](https://github.com/nosami/XSVim/files/3080721/Ide.2019-04-15__09-33-46.log)

**Comment by nosami** [comment] 2019-04-15 16:43
Thanks. Not seen this issue before, I'll look into it.

**Comment by nosami** [comment] 2019-04-15 17:14
Hmm... I just tried using the exact same versions that you are using and I can't reproduce VSMac 8.0.2.23 and XSVim 0.65.0.80. Not sure what is going wrong.

**Comment by bmatzelle** [comment] 2019-04-15 17:24
Unfortunately it's one of those bugs that shows itself only after I've been using the editor for a long time.  Once I restart VS then it goes away for a while.  Is there some sort of verbose debug mode that would give you more information?

**Comment by nosami** [comment] 2019-04-16 08:49
There is a verbose debug mode, yes. Run VSMac like this from the command line

```
MONODEVELOP_CONSOLE_LOG_LEVEL=All /Applications/Visual\ Studio.app/Contents/MacOS/VisualStudio --no-redirect
```

All the logging will go to the terminal instead of the usual log file. It is _very_ verbose :)

**Comment by bmatzelle** [comment] 2019-04-17 14:11
I'll be doing some heavy developing today so I'll try to reproduce it and use that verbose logging mode.

**Comment by bmatzelle** [comment] 2019-04-17 19:52
I managed to reproduce it in debug mode.  The debug log is attached.  

[XSVim_debug_jumps_issue.txt](https://github.com/nosami/XSVim/files/3091306/XSVim_debug_jumps_issue.txt)

**Comment by nosami** [comment] 2019-04-18 16:24
@bmatzelle Thanks for that. I don't see anything immediately obvious though. I'll keep trying to repro.

**Comment by bmatzelle** [comment] 2019-04-18 17:29
Great.  Thank you.

**Comment by nosami** [comment] 2019-04-18 18:16
Just saw this myself but didn't have the debugger attached at the time. Can't repro again :)

**Comment by nosami** [comment] 2019-10-17 12:57
Closing as H, M, L works perfectly in VsVim. I had to use a terrible hack to make this work with the old editor :)

https://github.com/VsVim/VsVim/pull/2733#issuecomment-538998555

**Closed as completed by nosami** 2019-10-17 12:57 UTC
