### ISSUE TITLE
Fix 'repeat' action

### ISSUE THREAD

**Issue by timorris** [nosami/XSVim#57] opened 2017-05-25 22:55 UTC
Currently the "." command repeats the last movement in NormalMode (so if you type "j" to move down one line, then type ".", it will just repeat the "j" thus moving down one line again, even though the last "change" I did was to "dd" which deletes a line), but it should repeat last change, with count replaced with [count]. Also it should repeat a yank command, when the 'y' flag is included.  So it seems that "state.lastAction" is being set incorrectly.  I think it should be set by "change" actions only.

http://vimdoc.sourceforge.net/htmldoc/repeat.html

**Comment by nosami** [comment] 2017-05-26 09:57
This is fixed in the latest version on the releases tab (0.23.0) https://github.com/nosami/XSVim/releases

It's not in the gallery yet because of issues with the build server. You can install the mpack file manually for now via `Visual Studio -> Extensions -> Install from File`

Thanks!

**Comment by nosami** [comment] 2017-05-26 10:05
This was reported in #41 with the fix [here](https://github.com/nosami/XSVim/commit/57e0d8ea1cdf19d3907f355cc15e7c820fc77bf3)

Currently not repeating `y` though.

**Comment by nosami** [comment] 2017-05-30 11:05
Is repeating yank useful? I can't think how I would use it.

If not, I'll close this ticket as the other points have already been addressed.

Thanks!

**Comment by timorris** [comment] 2017-05-30 13:55
Thanks for the response -- repeating the yank action itself isn't useful, really just the paste action.

... and for some reason, installing v0.23.3 is complaining that it cannot resolve dependencies:

"The selected add-ins can't be installed because there are dependency conflicts"

- MonoDevelop.Core v7.0
- MonoDevelop.Ide v7.0
- MonoDevelop.SourceEditor2 v7.0

I don't believe I had to install those before installing version 0.13 of  XSVim.  Does version 0.23.3 require those to be installed independently first?  

![screen shot 2017-05-30 at 10 25 50 am](https://cloud.githubusercontent.com/assets/3472614/26588159/7220070c-4522-11e7-9109-184a9a0b1871.png)

**Comment by nosami** [comment] 2017-05-30 15:25
Oh... the new version only works in Visual Studio for Mac. Can you install that?

The issue is that the Addin codebase changed significantly for VS for Mac, and I don't want to update 2 code bases.

**Comment by timorris** [comment] 2017-05-30 16:20
Ah okay will do thanks!

**Comment by nosami** [comment] 2017-05-30 16:22
thanks! v0.24.0 is currently in the VS for Mac extension gallery, so you should be ok with that

**Closed as completed by nosami** 2017-05-30 16:22 UTC
