### ISSUE TITLE
Yank/paste/clipboard should be consistent with other Vim editors

### ISSUE THREAD

**Issue by bmatzelle** [nosami/XSVim#255] opened 2019-04-22 18:33 UTC
I believe that XSVim support of yank (Y/y) and paste (P/p) should be consistent with other Vim emulation implementations.  Both [VSCodeVim](https://github.com/VSCodeVim/Vim) and [SublimeText Vim](https://www.sublimetext.com/docs/3/vintage.html) manage two clipboards: 

1. The Mac system clipboard
2. A Vim-only clipboard

So the app should behave thusly:

- Copying text (cmd-C) should add text to the Mac clipboard
- Pasting text (cmd-V) should paste text from the Mac clipboard
- Using Vim-mode yank (y/Y) should add to text to a Vim-only clipboard (and not replace the Mac clipboard text)
- Using Vim-mode paste (p) should paste text from the Vim-only clipboard

**Comment by nosami** [comment] 2019-04-23 08:07
Yes, I'll add this feature. I'll probably add a toggle to keep the current behaviour as I prefer it, but I realise that not everyone does!

I think this is a duplicate of https://github.com/nosami/XSVim/issues/245

**Comment by bmatzelle** [comment] 2019-04-23 12:56
Thanks!

**Comment by nosami** [comment] 2019-04-23 13:30
I should probably add support for yanking into _any_ vim register at the same time.

**Comment by nosami** [comment] 2019-10-17 12:55
This feature won't make it into XSVim. However, it works already in the VsVim port VsVim/VsVim#2733 (comment)

**Closed as completed by nosami** 2019-10-17 12:55 UTC
